name: pin_grow
description: "핀그로우입니다"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  carousel_slider: ^5.1.1
  dots_indicator: ^4.0.1
  fl_chart: ^1.1.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_hooks: ^0.21.3+1
  flutter_native_splash: ^2.4.6
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.0
  fluttertoast: ^8.2.12
  go_router: ^16.2.1
  google_fonts: ^6.3.1
  hooks_riverpod: ^2.6.1
  http: ^1.5.0
  icalendar_parser: ^2.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  kakao_flutter_sdk_user: ^1.9.7+3
  linear_progress_bar: ^1.2.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  table_calendar: ^3.2.0
  url_launcher: ^6.3.2
  web_socket_channel: ^3.0.3
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  flutter_launcher_icons: ^0.14.4
  riverpod_lint: ^2.6.5


flutter_launcher_icons:
  android: true
  ios: true 
  image_path: "assets/icons/app_icon.png" 
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon.png" 
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"
  

flutter:
  uses-material-design: true

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Thin.woff
          weight: 100
        - asset: assets/fonts/Pretendard/Pretendard-ExtraLight.woff
          weight: 200
        - asset: assets/fonts/Pretendard/Pretendard-Light.woff
          weight: 300
        - asset: assets/fonts/Pretendard/Pretendard-Regular.woff
          weight: 400
        - asset: assets/fonts/Pretendard/Pretendard-Medium.woff
          weight: 500
        - asset: assets/fonts/Pretendard/Pretendard-SemiBold.woff
          weight: 600
        - asset: assets/fonts/Pretendard/Pretendard-Bold.woff
          weight: 700
        - asset: assets/fonts/Pretendard/Pretendard-ExtraBold.woff
          weight: 800
        - asset: assets/fonts/Pretendard/Pretendard-Black.woff
          weight: 900

  assets:
    - .env
    - assets/logo/
    - assets/icons/
    - assets/characters/
    - assets/kakao_login/ko/
    - assets/region/
    - assets/region_logo/
    - assets/dummy/
    - assets/trip/
    - assets/shopping/